require 'rake'
require 'spec/rake/spectask'

desc "Run all examples"
Spec::Rake::SpecTask.new('examples') do |t|
  t.spec_files = FileList['../**/spec/**/*-spec.rb']
  t.rcov = true
  t.rcov_opts = ['--exclude', 'spec']
end
